### ISSUE TITLE
Reusing this for kmadathil/sanksrit_parser

### ISSUE THREAD

**Issue by kmadathil** [drdhaval2785/inriaxmlwrapper#4]
@drdhaval2785  

Is this under active development? I would like to reuse if possible.

Following issues are seen
1)  upasargas = etree.parse('SL_upasargas.xml')
throws an error. No such file exists. There is an SL_preverbs.txt
2) Cannot import this directly as a module simple mod would be to change the last line to
```
if __name__ == "__main__":
        convertfromfile('sanskritinput.txt','analysedoutput.txt')
```

If you're not intending to support this, I'll reimplement based on your logic.

**Comment by drdhaval2785** [comment]
It is not under active development right now, but I am willing to take it
to a stable stage so that you do not have to reinvent the wheel.

**Comment by kmadathil** [comment]
Thanks! 
If you add me as a contributor, I can make minor changes with your concurrence.

**Comment by drdhaval2785** [comment]
This was reused in sanskrit_parser.
