### ISSUE TITLE
Running sanskritmark raises error

### ISSUE THREAD

**Issue by avinashvarna** [drdhaval2785/inriaxmlwrapper#8]
Running the script causes an error
Line 518, which is currently:
if i % 2 == 0 and i != len(dat): # Even members of datum are the words and odd members are word boundaries. Therefore, processing only even members. 
should have:
... i != (len(dat)-1)
to skip the last element, which is empty. i never reaches len(dat)

(I could have forked, fixed and created a pull request, but it seems too much of an overhead for such a small fix. My apologies).

**Comment by drdhaval2785** [comment]
Fixed
